### PR TITLE
Add normalizing paths for windows

### PR DESCRIPTION
**Pull request by srolel**
https://github.com/alexisvincent/systemjs-config-builder/issues/5

### CODE REVIEW

**Comment by srolel** [comment]
A bit of duplication, but didn't want to put it in `walkTree` nor make another pass over the registry just to normalize the paths.

**Comment by alexisvincent** [comment]
Thanks! I think it needs a number of other places as well, like in System.config. Is there not a single place we can put this. Like when building out the registry. Then we don't have to use it anywhere

**Comment by srolel** [comment]
Updated the patch, I think that's a good spot.

**Comment by alexisvincent** [comment]
can you jump on IM

**Comment by alexisvincent** [comment]
After looking at this, I think the real solution is to use [path.posix](https://nodejs.org/api/path.html#path_path_posix), instead of normal path

**Comment by alexisvincent** [comment]
@Mosho1 Can you test this?

**Comment by alexisvincent** [comment]
@Mosho1 I'm now using the posix version of path. Can you check that it fixed the window issue?

**Comment by srolel** [comment]
That seems to work, nice job

**Pull request closed without merging**
